### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by badlydrawnface** [MedaiP90/gnome-sur-clock#5]
The gnome extensions page was taken down. What happened? Is this project dead?

![image](https://github.com/MedaiP90/gnome-sur-clock/assets/53501005/5504a457-d568-403e-b53c-60f36cfd68c9)

**Comment by MedaiP90** [comment]
I've reopened the page, but I'm not following the new releases of GNOME or actively adding features to the project. 

Anyway, I'll manage the pull requests if any.
